name: openai_package
description: Dart SDK for openAI Apis (Chat & Image & Transcription & Voice and Embeddings), integrate OpenAI products into your Flutter application.
version: 1.0.6
homepage: https://github.com/Enderjua/openai_package
repository: https://github.com/Enderjua/openai_package
documentation: https://github.com/Enderjua/openai_package/blob/main/README.md
issue_tracker: https://github.com/enderjua/openai_package/issues


environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  http_parser: ^4.0.2
  path: ^1.8.3


dev_dependencies:
  test: ^1.18.0
